_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 4
  BASE_LR: 0.02
  STEPS: (69600, 92800)
  MAX_ITER: 116000
  WARMUP_ITERS: 3625
TEST:
  EVAL_PERIOD: 29000
VIS_PERIOD: 2320
DATASETS:
  TRAIN: ('KITTI_train',)
  TEST: ('KITTI_val',) 
  CATEGORY_NAMES: ('pedestrian', 'car', 'cyclist')
  #CATEGORY_NAMES: ('cyclist', 'pedestrian', 'trailer', 'bus', 'motorcycle', 'car', 'barrier', 'truck', 'van', 'traffic cone', 'bicycle')
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 50